name: GitHub Classroom Workflow

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/*'
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  Checking-Solution:
    runs-on: gtest
    timeout-minutes: 3
    steps:
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Check repository clean
        run: ./scripts/check_clean.sh
      - name: Check requirements
        run: |
             !(grep -qwRE --include=*.{cc,cpp,h,hpp} '<vector>|<list>|<string>|<algorithm>|<stack>|<queue>|<deque>|<set>|<map>|<bits' ./* ) &&  (echo \"Check - OK\" )  || ( echo \"Forbiden STL containers\" && exit 9 )
      - name: Check code style
        run: |
             clang-format --version
             find "." \( -name '*.cpp' -o -name '*.h*' \) -print0 | xargs -0 clang-format --dry-run --Werror --verbose
      - name: Code linting
        uses: amcp-pit/cpp-linter@v1
        with:
          extra-args-before: '-xc++'
          extra-args: '-std=c++20'
          after-args: '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
      - name: Build
        run: ./scripts/build.sh
      - name: Test 1
        id: test-1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 1
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test01.in output.txt && cmp output.txt tests/test01.out"
          timeout: 1
          max-score: 1
      - name: Test 2
        id: test-2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 2
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test02.in output.txt && cmp output.txt tests/test02.out"
          timeout: 1
          max-score: 1
      - name: Test 3
        id: test-3
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 3
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test03.in output.txt && cmp output.txt tests/test03.out"
          timeout: 1
          max-score: 1
      - name: Test 4
        id: test-4
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 4
          setup-command: ''
          command: "timeout 1  ./build/gcd tests/test04.in output.txt && cmp output.txt tests/test04.out"
          timeout: 1
          max-score: 1
      - name: Test 5
        id: test-5
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 5
          setup-command: ''
          command: "timeout 1  ./build/gcd tests/test05.in output.txt && cmp output.txt tests/test05.out"
          timeout: 1
          max-score: 1
      - name: Test 6
        id: test-6
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 6
          setup-command: ''
          command: "timeout 1  ./build/gcd tests/test06.in output.txt && cmp output.txt tests/test06.out"
          timeout: 1
          max-score: 1
      - name: Test 7
        id: test-7
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 7
          setup-command: ''
          command: "timeout 1  ./build/gcd tests/test07.in output.txt && cmp output.txt tests/test07.out"
          timeout: 1
          max-score: 1
      - name: Test 8
        id: test-8
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 8
          setup-command: ''
          command: "timeout 1  ./build/gcd tests/test08.in output.txt && cmp output.txt tests/test08.out"
          timeout: 1
          max-score: 1
      - name: Test 9
        id: test-9
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 9
          setup-command: ''
          command: "timeout 1  ./build/gcd tests/test09.in output.txt && cmp output.txt tests/test09.out"
          timeout: 1
          max-score: 1
      - name: Test 10
        id: test-10
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 10
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test10.in output.txt && cmp output.txt tests/test10.out"
          timeout: 1
          max-score: 1
      - name: Test 11
        id: test-11
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 11
          setup-command: 'cp -f ~/ads-tests/gcdonsegment/*.* ./tests/ && echo "Tests added"'
          command: "timeout 1 ./build/gcd tests/test11.in output.txt && cmp output.txt tests/test11.out"
          timeout: 1
          max-score: 1
      - name: Test 12
        id: test-12
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 12
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test12.in output.txt && cmp output.txt tests/test12.out"
          timeout: 1
          max-score: 1
      - name: Test 13
        id: test-13
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 13
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test13.in output.txt && cmp output.txt tests/test13.out"
          timeout: 1
          max-score: 1
      - name: Test 14
        id: test-14
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 14
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test14.in output.txt && cmp output.txt tests/test14.out"
          timeout: 1
          max-score: 1
      - name: Test 15
        id: test-15
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 15
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test15.in output.txt && cmp output.txt tests/test15.out"
          timeout: 1
          max-score: 1
      - name: Test 16
        id: test-16
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 16
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test16.in output.txt && cmp output.txt tests/test16.out"
          timeout: 1
          max-score: 1
      - name: Test 17
        id: test-17
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 17
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test17.in output.txt && cmp output.txt tests/test17.out"
          timeout: 1
          max-score: 1
      - name: Test 18
        id: test-18
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 18
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test18.in output.txt && cmp output.txt tests/test18.out"
          timeout: 1
          max-score: 1
      - name: Test 19
        id: test-19
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 19
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test19.in output.txt && cmp output.txt tests/test19.out"
          timeout: 1
          max-score: 1
      - name: Test 20
        id: test-20
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 20
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test20.in output.txt && cmp output.txt tests/test20.out"
          timeout: 1
          max-score: 1
      - name: Test 21
        id: test-21
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 21
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test21.in output.txt && cmp output.txt tests/test21.out"
          timeout: 1
          max-score: 1
      - name: Test 22
        id: test-22
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 22
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test22.in output.txt && cmp output.txt tests/test22.out"
          timeout: 1
          max-score: 1
      - name: Test 23
        id: test-23
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 23
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test23.in output.txt && cmp output.txt tests/test23.out"
          timeout: 1
          max-score: 1
      - name: Test 24
        id: test-24
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Test 24
          setup-command: ''
          command: "timeout 1 ./build/gcd tests/test24.in output.txt && cmp output.txt tests/test24.out"
          timeout: 1
          max-score: 1
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
          TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
          TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
          TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
          TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
          TEST-6_RESULTS: "${{steps.test-6.outputs.result}}"
          TEST-7_RESULTS: "${{steps.test-7.outputs.result}}"
          TEST-8_RESULTS: "${{steps.test-8.outputs.result}}"
          TEST-9_RESULTS: "${{steps.test-9.outputs.result}}"
          TEST-10_RESULTS: "${{steps.test-10.outputs.result}}"
          TEST-11_RESULTS: "${{steps.test-11.outputs.result}}"
          TEST-12_RESULTS: "${{steps.test-12.outputs.result}}"
          TEST-13_RESULTS: "${{steps.test-13.outputs.result}}"
          TEST-14_RESULTS: "${{steps.test-14.outputs.result}}"
          TEST-15_RESULTS: "${{steps.test-15.outputs.result}}"
          TEST-16_RESULTS: "${{steps.test-16.outputs.result}}"
          TEST-17_RESULTS: "${{steps.test-17.outputs.result}}"
          TEST-18_RESULTS: "${{steps.test-18.outputs.result}}"
          TEST-19_RESULTS: "${{steps.test-19.outputs.result}}"
          TEST-20_RESULTS: "${{steps.test-20.outputs.result}}"
          TEST-21_RESULTS: "${{steps.test-21.outputs.result}}"
          TEST-22_RESULTS: "${{steps.test-22.outputs.result}}"
          TEST-23_RESULTS: "${{steps.test-23.outputs.result}}"
          TEST-24_RESULTS: "${{steps.test-24.outputs.result}}"
        with:
          runners: test-1,test-2,test-3,test-4,test-5,test-6,test-7,test-8,test-9,test-10,test-11,test-12,test-13,test-14,test-15,test-16,test-17,test-18,test-19,test-20,test-21,test-22,test-23,test-24
      - name: Memory leaks
        run: |
             valgrind --tool=memcheck --leak-check=full --undef-value-errors=no --error-exitcode=111 ./build/gcd tests/test10.in output.txt
      - name: Checkout
        uses: actions/checkout@v4
      - name: CPD
        uses: amcp-pit/cpd-action@v1
        id: cpd
        with:
          repository: ${{ github.repository }}
          collection: ${{ github.repository_owner  }}
      - name: Clean
        run: |
             rm -rf ./* || true
             rm -rf ./.??* || true
